version: "3.9"

services:
  app:
    build: .
    volumes:
      - .:/code
    env_file:
      - .env.docker
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
#      - DATABASE_URL=postgres://admin:1Qazxsw@@db:5432/postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1Qazxsw@