# Generated by Django 3.2.15 on 2023-01-12 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Etap produkcji', max_length=250, unique=True, verbose_name='Etap')),
            ],
            options={
                'verbose_name': 'etap',
                'verbose_name_plural': 'etap',
                'db_table': 'stage',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa zlecenia', max_length=250, unique=True, verbose_name='Zlecenie')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data dodania', verbose_name='Utworzony')),
                ('deadline', models.DateTimeField(help_text='Termin wykonania', verbose_name='Deadline')),
                ('completed', models.BooleanField(default=False, help_text='Czy zlecenie zakończone', verbose_name='Ukończony')),
                ('stage', models.ForeignKey(help_text='Etap wykonania zlecenia', on_delete=django.db.models.deletion.CASCADE, to='app.stage', verbose_name='Etap')),
            ],
            options={
                'verbose_name': 'zlecenie',
                'verbose_name_plural': 'zlecenie',
                'db_table': 'order',
            },
        ),
    ]
