# Generated by Django 3.2.15 on 2023-01-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230124_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='angels_extras',
            field=models.BooleanField(default=False, help_text='Anioły', verbose_name='Anioły'),
        ),
    ]
