# Generated by Django 3.2.15 on 2023-01-26 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa zlecenia, Anioły', max_length=250, unique=True, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, help_text='Szczegółowy opis zamówienia', verbose_name='Opis')),
                ('email', models.EmailField(blank=True, help_text='Adres email', max_length=254, null=True, verbose_name='adres email')),
                ('phone', models.CharField(blank=True, help_text='Kontaktowy nr telefonu w formacie 123456789', max_length=9, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{9,15}$')], verbose_name='nr telefonu')),
                ('deadline_angel', models.DateField(blank=True, help_text='Deadline anioły', null=True, verbose_name='Deadline anioły')),
            ],
            options={
                'verbose_name': 'Anioły',
                'verbose_name_plural': 'Anioły',
                'db_table': 'angel',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Etap wykonania zlecenia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.stage', verbose_name='Etap'),
        ),
    ]
