# Generated by Django 3.2.15 on 2023-01-26 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230126_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='angels_extras',
            field=models.ForeignKey(blank=True, help_text='Zlecenie na anioły', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.angel', verbose_name='Angel'),
        ),
    ]
